version: "3.8"

x-environment:
  &default-labels
  org.opencontainers.image.authors: ${AUTHOR}
  org.opencontainers.image.created: ${BUILD_DATE_RFC339}
  org.opencontainers.image.licenses: ${LICENSE}
  org.opencontainers.image.revision: ${COMMIT_HASH}
  org.opencontainers.image.source: ${REPOSITORY}
  org.opencontainers.image.url: ${REPOSITORY}
  org.opencontainers.image.vendor: CNPEM
  org.opencontainers.image.version: ${COMMIT_HASH}


services:
  epics-modules:
    image: epics-modules
    build:
      context: .
      dockerfile: Dockerfile
      target: epics-modules

  ioc:
    image: dockerregistry.lnls-sirius.com.br/gas/${IOC_REPO}:${IOC_COMMIT}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        <<: *default-labels
      args:
        IOC_COMMIT: ${IOC_COMMIT}
        IOC_GROUP: ${IOC_GROUP}
        IOC_REPO: ${IOC_REPO}
